[SERVICE]
    Flush         1
    Grace         10
    Log_Level     error
    Parsers_File  /fluent-bit/etc/tirodhan-parsers.conf

[INPUT]
    Name              tail
    Path              ${LOG_SHARED_DIR}/*.jsonl
    Parser            tirodhan-json
    Tag               tirodhan
    Read_from_Head    On
    Refresh_Interval  1
    Mem_Buf_Limit     8M
    Skip_Long_Lines   On

[OUTPUT]
    Name                  azure_blob
    Match                 tirodhan
    Account_Name          ${LOG_ACCOUNT_NAME}
    Container_Name        app-logs
    Auth_Type             sas
    Sas_Token             ${LOG_SAS}
    Tls                   On
    Tls.Verify            On
    Tls.Verify_Hostname   On
    Auto_Create_Container Off
    Blob_Type             blockblob
    Compress_Blob         On
    Buffering_Enabled     On
    Buffer_Dir            /tmp/tirodhan-blob
    Database_File         /tmp/tirodhan-blob.db
    Store_Dir_Limit_Size   32M
    Upload_File_Size      1M
    Upload_Timeout        1m
    Io_Timeout            5s
    Path                  nonprod/${LOG_WORKLOAD}
