"""Queued financial evidence, account scan controls and immutable financial identities."""

import sqlalchemy as sa
from alembic import op

revision = "0021_financial_correctness"
down_revision = "0020_financial_reconciliation"
branch_labels = None
depends_on = None


def _reservation_sql(guard_legacy: bool) -> str:
    legacy = (
        """
      IF NEW.captured_charge_id IS NULL THEN
        SELECT cc.* INTO c FROM captured_charge cc
          JOIN payment_attempt a ON a.payment_attempt_id=cc.payment_attempt_id
          WHERE cc.payment_attempt_id=NEW.payment_attempt_id
            AND a.provider_payment_id=cc.provider_payment_id
            AND cc.payment_id=NEW.payment_id AND cc.provider=NEW.provider
          FOR UPDATE OF cc;
        IF NOT FOUND THEN RETURN NEW; END IF;
        is_legacy := true;
        SELECT * INTO o FROM refund_obligation WHERE captured_charge_id=c.captured_charge_id;
      ELSE
        SELECT * INTO c FROM captured_charge
          WHERE captured_charge_id=NEW.captured_charge_id FOR UPDATE;
        SELECT * INTO o FROM refund_obligation WHERE refund_obligation_id=NEW.refund_obligation_id;
      END IF;
    """
        if guard_legacy
        else """
      IF NEW.captured_charge_id IS NULL THEN RETURN NEW; END IF;
      SELECT * INTO c FROM captured_charge
        WHERE captured_charge_id=NEW.captured_charge_id FOR UPDATE;
      SELECT * INTO o FROM refund_obligation WHERE refund_obligation_id=NEW.refund_obligation_id;
    """
    )
    payable = (
        "NOT (r.status='FAILED' AND r.non_payable_verified_at IS NOT NULL)"
        if guard_legacy
        else "r.non_payable_verified_at IS NULL"
    )
    return f"""
    CREATE OR REPLACE FUNCTION enforce_charge_refund_reservation()
      RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE c captured_charge%ROWTYPE; o refund_obligation%ROWTYPE;
      reserved bigint; is_legacy boolean := false;
    BEGIN
      {legacy}
      IF c.payment_id <> NEW.payment_id OR c.payment_attempt_id <> NEW.payment_attempt_id
         OR c.provider <> NEW.provider OR c.currency <> NEW.currency
         OR (NOT is_legacy AND o.refund_obligation_id IS NULL)
         OR (o.refund_obligation_id IS NOT NULL AND
           (o.captured_charge_id <> c.captured_charge_id OR o.payout_blocked
             OR o.amount_minor > c.amount_minor)) THEN
        RAISE EXCEPTION 'Invalid charge refund obligation' USING ERRCODE='23514';
      END IF;
      SELECT COALESCE(SUM(r.amount_minor),0) INTO reserved FROM refund r
      JOIN payment_attempt a ON a.payment_attempt_id=r.payment_attempt_id
      WHERE (r.captured_charge_id=c.captured_charge_id OR
        (r.captured_charge_id IS NULL AND a.payment_attempt_id=c.payment_attempt_id
          AND a.provider_payment_id=c.provider_payment_id))
      AND r.refund_id <> NEW.refund_id AND {payable};
      IF reserved + NEW.amount_minor > c.amount_minor
         OR reserved + NEW.amount_minor > COALESCE(o.amount_minor,c.amount_minor) THEN
        RAISE EXCEPTION 'Charge refund reservation exceeded' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    """


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_scan_checkpoint",
        sa.Column("financial_scan_checkpoint_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_account_key", sa.String(length=64), nullable=False),
        sa.Column("scan_kind", sa.String(length=24), nullable=False),
        sa.Column("window_start", sa.BigInteger(), nullable=False),
        sa.Column("window_end", sa.BigInteger(), nullable=False),
        sa.Column("page_offset", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pass_digest", sa.String(length=64), server_default="", nullable=False),
        sa.Column("previous_digest", sa.String(length=64), nullable=True),
        sa.Column("last_exhausted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.UUID(), nullable=True),
        sa.Column("claim_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "page_offset >= 0 AND window_end >= window_start", name="ck_financial_scan_bounds"
        ),
        sa.PrimaryKeyConstraint("financial_scan_checkpoint_id"),
        sa.UniqueConstraint(
            "provider", "provider_account_key", "scan_kind", name="uq_financial_scan"
        ),
    )
    op.create_table(
        "settlement_evidence",
        sa.Column("settlement_evidence_id", sa.Uuid(), nullable=False),
        sa.Column("provider_account_key", sa.String(length=64), nullable=False),
        sa.Column("observation_key", sa.String(length=64), nullable=False),
        sa.Column("provider_entity_id", sa.String(length=200), nullable=False),
        sa.Column("movement_type", sa.String(length=24), nullable=False),
        sa.Column("provider_settlement_id", sa.String(length=200), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=200), nullable=True),
        sa.Column("provider_dispute_id", sa.String(length=200), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("debit_minor", sa.BigInteger(), nullable=False),
        sa.Column("credit_minor", sa.BigInteger(), nullable=False),
        sa.Column("fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("settled", sa.Boolean(), nullable=False),
        sa.Column("on_hold", sa.Boolean(), nullable=False),
        sa.Column("provider_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("classification", sa.String(length=64), nullable=False),
        sa.Column("fee_includes_tax", sa.Boolean(), nullable=True),
        sa.Column("captured_charge_id", sa.UUID(), nullable=True),
        sa.Column("refund_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "amount_minor >= 0 AND debit_minor >= 0 AND credit_minor >= 0 "
            "AND fee_minor >= 0 AND tax_minor >= 0",
            name="ck_settlement_money",
        ),
        sa.ForeignKeyConstraint(
            ["captured_charge_id"],
            ["captured_charge.captured_charge_id"],
        ),
        sa.ForeignKeyConstraint(
            ["refund_id"],
            ["refund.refund_id"],
        ),
        sa.PrimaryKeyConstraint("settlement_evidence_id"),
        sa.UniqueConstraint(
            "provider_account_key", "observation_key", name="uq_settlement_observation"
        ),
    )
    op.create_index(
        "ix_settlement_review",
        "settlement_evidence",
        ["classification", "settlement_evidence_id"],
        unique=False,
    )
    op.create_index(
        "ix_settlement_unmapped_payment",
        "settlement_evidence",
        ["provider_payment_id"],
        postgresql_where=sa.text("refund_id IS NULL"),
    )
    op.add_column(
        "financial_exception", sa.Column("settlement_evidence_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "financial_exception",
        sa.Column("expected_settlement_id", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "financial_exception",
        sa.Column("expected_settlement_due_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_financial_exception_settlement_evidence",
        "financial_exception",
        "settlement_evidence",
        ["settlement_evidence_id"],
        ["settlement_evidence_id"],
    )
    op.create_unique_constraint(
        "uq_attempt_payment_owner", "payment_attempt", ["payment_attempt_id", "payment_id"]
    )
    op.create_foreign_key(
        "fk_payment_successful_attempt_owner",
        "payment",
        "payment_attempt",
        ["successful_attempt_id", "payment_id"],
        ["payment_attempt_id", "payment_id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.add_column(
        "payment_provider_event",
        sa.Column("provider_order_id", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "payment_provider_event",
        sa.Column("provider_refund_id", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "payment_provider_event",
        sa.Column("provider_dispute_id", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "payment_provider_event", sa.Column("dispute_status", sa.String(length=24), nullable=True)
    )
    op.add_column(
        "payment_provider_event", sa.Column("amount_deducted_minor", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "payment_provider_event", sa.Column("contradicted_event_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        "ix_provider_event_review",
        "payment_provider_event",
        ["processing_status", "payment_provider_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_provider_event_unmatched_payment",
        "payment_provider_event",
        ["provider", "provider_payment_id"],
        postgresql_where=sa.text("processing_status = 'UNMATCHED'"),
    )
    op.create_foreign_key(
        "fk_provider_event_contradicted",
        "payment_provider_event",
        "payment_provider_event",
        ["contradicted_event_id"],
        ["payment_provider_event_id"],
    )
    # The old Razorpay adapter always sent rf_<UUID hex> for these neutral keys.
    # Normalize that provable representation only; unknown keys are not guessed.
    op.execute(
        "UPDATE refund SET provider_idempotency_key='rf_' || replace(refund_id::text,'-','') "
        "WHERE provider='RAZORPAY' AND provider_idempotency_key='refund:' || refund_id::text"
    )
    op.execute("""
CREATE FUNCTION protect_capture_facts() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF ROW(OLD.payment_id,OLD.payment_attempt_id,OLD.provider,OLD.provider_payment_id,
        OLD.provider_order_id,OLD.provider_account_key,OLD.amount_minor,OLD.currency,
        OLD.evidence_id,OLD.captured_at) IS DISTINCT FROM
        ROW(NEW.payment_id,NEW.payment_attempt_id,NEW.provider,NEW.provider_payment_id,
        NEW.provider_order_id,NEW.provider_account_key,NEW.amount_minor,NEW.currency,
        NEW.evidence_id,NEW.captured_at) THEN
        RAISE EXCEPTION 'Captured financial facts are immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    """)
    op.execute("""
CREATE TRIGGER immutable_capture_facts BEFORE UPDATE OR DELETE ON captured_charge
      FOR EACH ROW EXECUTE FUNCTION protect_capture_facts();
    """)
    op.execute("""
CREATE FUNCTION protect_submitted_refund_identity() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF OLD.processing_started_at IS NOT NULL AND
        ROW(OLD.refund_id,OLD.payment_id,OLD.payment_attempt_id,OLD.provider,
          OLD.provider_idempotency_key,OLD.amount_minor,OLD.currency,OLD.captured_charge_id,
          OLD.processing_started_at) IS DISTINCT FROM
        ROW(NEW.refund_id,NEW.payment_id,NEW.payment_attempt_id,NEW.provider,
          NEW.provider_idempotency_key,NEW.amount_minor,NEW.currency,NEW.captured_charge_id,
          NEW.processing_started_at) THEN
        RAISE EXCEPTION 'Submitted refund identity is immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    """)
    op.execute("""
CREATE TRIGGER immutable_submitted_refund BEFORE UPDATE ON refund
      FOR EACH ROW EXECUTE FUNCTION protect_submitted_refund_identity();
    """)
    op.execute("""
CREATE FUNCTION protect_financial_audit() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'Financial audit is append-only' USING ERRCODE='23514';
    END $$;
    """)
    op.execute("""
CREATE TRIGGER immutable_financial_audit BEFORE UPDATE OR DELETE ON financial_audit
      FOR EACH ROW EXECUTE FUNCTION protect_financial_audit();
    """)
    op.execute("""
CREATE TRIGGER immutable_settlement_evidence BEFORE UPDATE OR DELETE ON settlement_evidence
      FOR EACH ROW EXECUTE FUNCTION protect_financial_audit();
    """)
    op.execute("""
CREATE FUNCTION protect_provider_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'DELETE' OR
        ROW(OLD.provider,OLD.external_event_id,OLD.event_type,OLD.payload_hash,
          OLD.received_at,OLD.evidence_source,OLD.provider_account_key,
          OLD.observed_outcome,OLD.provider_payment_id,OLD.provider_order_id,
          OLD.provider_refund_id,OLD.amount_minor,OLD.currency,OLD.provider_dispute_id,
          OLD.dispute_status,OLD.amount_deducted_minor,OLD.definitive_non_payable) IS DISTINCT FROM
        ROW(NEW.provider,NEW.external_event_id,NEW.event_type,NEW.payload_hash,
          NEW.received_at,NEW.evidence_source,NEW.provider_account_key,
          NEW.observed_outcome,NEW.provider_payment_id,NEW.provider_order_id,
          NEW.provider_refund_id,NEW.amount_minor,NEW.currency,NEW.provider_dispute_id,
          NEW.dispute_status,NEW.amount_deducted_minor,NEW.definitive_non_payable) THEN
        RAISE EXCEPTION 'Provider observation facts are immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    """)
    op.execute("""
CREATE TRIGGER immutable_provider_evidence BEFORE UPDATE OR DELETE ON payment_provider_event
      FOR EACH ROW EXECUTE FUNCTION protect_provider_evidence();
    """)
    for table, name in (
        ("captured_charge", "fk_capture_attempt_owner"),
        ("refund", "fk_refund_attempt_owner"),
    ):
        op.create_foreign_key(
            name,
            table,
            "payment_attempt",
            ["payment_attempt_id", "payment_id"],
            ["payment_attempt_id", "payment_id"],
        )
    op.execute(_reservation_sql(True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Export scan/report/conflict facts before any real rollback. Original entities survive.
    op.execute(_reservation_sql(False))
    op.drop_constraint("fk_capture_attempt_owner", "captured_charge", type_="foreignkey")
    op.drop_constraint("fk_refund_attempt_owner", "refund", type_="foreignkey")
    op.execute("DROP TRIGGER IF EXISTS immutable_provider_evidence ON payment_provider_event")
    op.execute("DROP FUNCTION IF EXISTS protect_provider_evidence()")
    op.execute("DROP TRIGGER immutable_settlement_evidence ON settlement_evidence")
    op.execute("DROP TRIGGER immutable_financial_audit ON financial_audit")
    op.execute("DROP FUNCTION protect_financial_audit()")
    op.execute("DROP TRIGGER immutable_submitted_refund ON refund")
    op.execute("DROP FUNCTION protect_submitted_refund_identity()")
    op.execute("DROP TRIGGER immutable_capture_facts ON captured_charge")
    op.execute("DROP FUNCTION protect_capture_facts()")
    # Keep normalized native keys: the old adapter sends the same rf_<UUID> anyway.

    op.drop_constraint(
        "fk_provider_event_contradicted", "payment_provider_event", type_="foreignkey"
    )
    op.drop_index("ix_provider_event_review", table_name="payment_provider_event")
    op.execute("DROP INDEX IF EXISTS ix_provider_event_unmatched_payment")
    op.drop_column("payment_provider_event", "contradicted_event_id")
    op.drop_column("payment_provider_event", "amount_deducted_minor")
    op.drop_column("payment_provider_event", "dispute_status")
    op.drop_column("payment_provider_event", "provider_dispute_id")
    op.drop_column("payment_provider_event", "provider_refund_id")
    op.drop_column("payment_provider_event", "provider_order_id")
    op.drop_constraint("fk_payment_successful_attempt_owner", "payment", type_="foreignkey")
    op.drop_constraint("uq_attempt_payment_owner", "payment_attempt", type_="unique")
    op.drop_constraint(
        "fk_financial_exception_settlement_evidence", "financial_exception", type_="foreignkey"
    )
    op.drop_column("financial_exception", "expected_settlement_due_at")
    op.drop_column("financial_exception", "expected_settlement_id")
    op.drop_column("financial_exception", "settlement_evidence_id")
    op.drop_index("ix_settlement_review", table_name="settlement_evidence")
    op.execute("DROP INDEX IF EXISTS ix_settlement_unmapped_payment")
    op.drop_table("settlement_evidence")
    op.drop_table("financial_scan_checkpoint")
